### ISSUE TITLE
IItemstack Compatibility

### ISSUE THREAD

**Issue by NielsPilgaard** [Shadows-of-Fire/HitWithAxe#1]
Hey o/

Would it be possible to add a method (IItemStack, IItemStack, optional IItemstack) in addition to the existing ones? I'm attempting to make Chopping recipes in bulk, most importantly Plank to Slab conversion, and that would be a lot easier with IItemStacks.

I hope you'll consider it :)

**Comment by Shadows-of-Fire** [comment]
Ah yeah, probably.  Its setup defensively (not all blocks have an item form) since it has to convert directly to IBlockState.

**Comment by NielsPilgaard** [comment]
Ah I see, I hope there's a safe-ish way around that. IIngridient would be a good alternative to IItemStack, if that's preferable to make.

**Comment by Shadows-of-Fire** [comment]
IIngredient would be even more difficult, as its a `Predicate<ItemStack>`, while this mod needs a `Predicate<IBlockState>`.  The conversion from itemstack -> blockstate doesn't always happen nicely, but I can work wrapping IItemStack into the function lists.

**Comment by Shadows-of-Fire** [comment]
HitWithAxe-1.1.0 pending, hopefully those functions work properly.

**Comment by NielsPilgaard** [comment]
Thank you, I'll check it out asap!

**Comment by NielsPilgaard** [comment]
It works, woo!

**Comment by Shadows-of-Fire** [comment]
👏
