### ISSUE TITLE
Debarked Logs

### ISSUE THREAD

**Issue by gary-conlon** [Shadows-of-Fire/HitWithAxe#2]
How do you actually get this block, because hitting it with an axe does not seem to work. @Shadows-of-Fire

**Comment by Shadows-of-Fire** [comment]
This mod does nothing without scripts.  The default script for all added logs is on the cf page.

**Comment by gary-conlon** [comment]
I have added the scripts in, but do I need to add a script to allow the axe to strip the logs.

**Comment by Shadows-of-Fire** [comment]
If the scripts are present an action should be triggered off of axe right click

**Comment by gary-conlon** [comment]
No i've tried in survival and creative and nothing happens.

**Comment by gary-conlon** [comment]
im using only the default scripts https://github.com/Shadows-of-Fire/HitWithAxe/blob/master/DefaultScript.zs

**Comment by Shadows-of-Fire** [comment]
I'm receiving no issues with the default script, you may have some other mod preventing the right click event.
