### ISSUE TITLE
Additional Log Types

### ISSUE THREAD

**Issue by NielsPilgaard** [Shadows-of-Fire/HitWithAxe#3]
Hello o/ 

Would you be willing to add Debarked versions of Natura and Rustic trees, if I supplied the textures? :)

**Comment by Shadows-of-Fire** [comment]
Yeah, if you have textures it'll go quite quickly.

**Comment by NielsPilgaard** [comment]
Awesome, I'll fire up a pull request. The top of the debarked logs use textures from Natura / Rustic, do you think that will be an issue?

**Comment by NillerMedDild** [comment]
Cool, I'll make a pull request if I can get it to work.

**Comment by NillerMedDild** [comment]
I can't seem to fork the repository, is there something preventing it?

**Comment by Shadows-of-Fire** [comment]
The requested logs were added.  The bark items are also present.  However, I don't have the time to create the default scripts for those logs - I trust you can do that on your own.

**Comment by NielsPilgaard** [comment]
Thank you! 
Yep, I'll submit a PR when I'm done.

**Comment by NielsPilgaard** [comment]
I see the textures are a bit off, I'll fix those in the upcoming PR too.
