### ISSUE TITLE
Nature's Aura Compatibility

### ISSUE THREAD

**Issue by NielsPilgaard** [Shadows-of-Fire/HitWithAxe#7]
Hello!

I would like to request compatibility for Nature's Aura's only tree :)
I made the textures:
[ancient_tree.zip](https://github.com/Shadows-of-Fire/HitWithAxe/files/2918955/ancient_tree.zip)

**Comment by Shadows-of-Fire** [comment]
Done.  Will be released in 1.4.0.  Default script wasn't updated, but I trust you can figure that out.

**Comment by NielsPilgaard** [comment]
Thank you!
