### ISSUE TITLE
JEI Issues

### ISSUE THREAD

**Issue by NielsPilgaard** [Shadows-of-Fire/HitWithAxe#8]
Hey!

It looks like JEI compatibility doesn't work in HitWithAxe, and Debarked Logs don't even display in JEI.

### Versions
- jei_1.12.2-4.15.0.268
- Hit With Axe-1.12.2-1.4.0

**Comment by Shadows-of-Fire** [comment]
Thats uh, weird. To say the least.  You sure something else isn't breaking it?
Unless jei changed some internals theres no reason it would just stop working.

**Comment by NielsPilgaard** [comment]
I'll do some additional tests this evening (about 5 hours from now), but I don't have any scripts that would tamper with Debarked Logs in JEI, unless adding a description to them hides them from JEI.

I'll also try with a fresh install of HitWithAxe + JEI

**Comment by NielsPilgaard** [comment]
So the Debarked Logs show up in an instance with only Crafttweaker, JEI, Placebo and HitWithAxe. 

Is the way to obtain Bark/Debarked Logs supposed so show up in JEI, or only the blocks themselves?

**Comment by Shadows-of-Fire** [comment]
Without the script it won't show any recipes, but if you have it, it will.

**Comment by Shadows-of-Fire** [comment]
I was told the integrations are fully functional in FTB Interactions earlier today

**Comment by NielsPilgaard** [comment]
Alright, my apologies.
